In [9]:

# First access the VTK module (and any other needed modules) by importing them.
# noinspection PyUnresolvedReferences
import vtkmodules.vtkRenderingOpenGL2
from vtkmodules.vtkCommonColor import vtkNamedColors
from vtkmodules.vtkCommonTransforms import vtkTransform
from vtkmodules.vtkFiltersSources import vtkSphereSource
from vtkmodules.vtkFiltersSources import vtkLineSource
from vtkmodules.vtkFiltersCore import vtkTubeFilter
from vtkmodules.vtkInteractionStyle import vtkInteractorStyleTrackballCamera
from vtkmodules.vtkInteractionWidgets import vtkBoxWidget
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer
)

In [32]:
import math
import numpy as np

In [58]:
colors = vtkNamedColors()

sphere = vtkSphereSource()
sphereCentre = np.array([ 0, 0, 0 ])
sphereRadius = 5.0
sphere.SetCenter( sphereCentre.tolist() )
sphere.SetRadius( sphereRadius )
sphere.SetPhiResolution( 20 )
sphere.SetThetaResolution( 20 )

sphereMapper = vtkPolyDataMapper()
sphereMapper.SetInputConnection( sphere.GetOutputPort() )

sphereActor = vtkActor()
sphereActor.SetMapper( sphereMapper )
sphereActor.GetProperty().SetColor( colors.GetColor3d('Bisque') )

In [59]:
line = vtkLineSource()
point1 = np.array([10,0,0])
point2 = np.array([-10, 0, 0])
v = point2 - point1
v = v/np.linalg.norm( v )
print(v)
print(point1.tolist())
line.SetPoint1( point1.tolist() )
line.SetPoint2( point2.tolist() )

tube = vtkTubeFilter()
tube.SetInputConnection( line.GetOutputPort() )
tube.SetRadius( 0.1 )
tube.SetNumberOfSides(10)

lineMapper = vtkPolyDataMapper()
lineMapper.SetInputConnection( tube.GetOutputPort() )
 
lineActor = vtkActor()
lineActor.SetMapper( lineMapper )

[-1.  0.  0.]
[10, 0, 0]


In [60]:
## calculate the intersection
PC = point1 - sphereCentre
determinant = np.dot(v, PC) * np.dot(v, PC) - np.dot(PC,PC) + sphereRadius * sphereRadius
print(PC)
print( determinant )

if determinant > 0:
    a = -1 * np.dot( v, PC)
    t1 = a + math.sqrt( determinant )
    L1 = point1 + t1 * v
    t2 = a - math.sqrt( determinant )
    L2 = point1 + t2 * v
    print(L1, L2)

[10  0  0]
25.0
[-5.  0.  0.] [5. 0. 0.]


In [64]:
s1 = vtkSphereSource()
s1.SetCenter( L1.tolist() )
s1.SetRadius( 0.4 )

s1Mapper = vtkPolyDataMapper()
s1Mapper.SetInputConnection( s1.GetOutputPort())

s1Actor = vtkActor()
s1Actor.SetMapper( s1Mapper )
s1Actor.GetProperty().SetColor( colors.GetColor3d('Red'))

s2 = vtkSphereSource()
s2.SetCenter( L2.tolist() )
s2.SetRadius( 0.4 )

s2Mapper = vtkPolyDataMapper()
s2Mapper.SetInputConnection( s2.GetOutputPort())

s2Actor = vtkActor()
s2Actor.SetMapper( s2Mapper )
s2Actor.GetProperty().SetColor( colors.GetColor3d('Red'))


In [65]:

ren = vtkRenderer()
ren.AddActor( sphereActor )
ren.AddActor( lineActor )
ren.AddActor( s1Actor )
ren.AddActor( s2Actor )
ren.SetBackground( colors.GetColor3d('MidnightBlue'))


renWin = vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(640, 480)
renWin.SetWindowName('AISE 4020')

iren = vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)


In [66]:

iren.Initialize()
iren.Start()