## Transforms

In linear algebra, transform (or <wiki:transformation_matrix>) is used to specify the geometrical relationship between two <wiki:cartesian_coordinate_system>. There are many use cases:
- Co-registration between {term}`CT` and {term}`MRI> volumes
- Specify the {term}`3D` location of an object using tracking systems,
- Tool calibration, e.g. specifying the location of the tip of surgical drill with respect to the tracking sensor, etc.

That is, in an {term}`IGI` surgical workflow, there are always multiple **rigid bodies**, i.e. <wiki:cartesian_coordinate_system> present:
- Target anatomy (spine),
- Surgical tool (needle),
- Live image or video {term}`US`) and
- Geometrical model or representation of anatomy (e.g. surface model derived from {term}`CT`)

We must keep track of them all the time by understanding how each of these <wiki:cartesian_coordinate_system> are related with each other.

## Translation

The simplest transform is moving a object from one location to another, i.e. a [translation](https://en.wikipedia.org/wiki/Translation_(geometry)).

Let the initial position of an object be $p$, and let $v$ be a *translation vector*, then the new position of the object $q$ after translation by $v$ is:

$$
q = p + v
$$

If both $p$ and $v$ are multi-dimensional, then this is equivalant to vector addition. In {term}`3D`, we have
$$
\begin{align}
q_x & = & q_x + v_x\\
q_y & = & q_y + v_y\\
q_z & = & q_z + v_z
\end{align}
$$




In Python, we can simply use the standard addition operation:

In [8]:
import math
import numpy as np 
import numpy.matlib

p = np.array([ 1, 0, 0 ])      # This is a ROW vector
p = p.reshape(-1, 1)           # this is a COLUMN vector
p = np.array([ [0],[1],[0] ])  # alternative

v = np.array( [4, 5, 6] ).reshape(-1,1)
q = p + v

print("The initial position is:\n", p, 
"\nafter translation by:\n", v,
"\nis now located at:\n", q)

The initial position is:
 [[0]
 [1]
 [0]] 
after translation by:
 [[4]
 [5]
 [6]] 
is now located at:
 [[4]
 [6]
 [6]]


For visualization and other implementations, consult the following [tutorial](#ref_tutorial_translation).