# Math Primer

## Cartesian Coordinates and Vector Geometry
Linear algebra, particularly Cartesian coordinate systems and vector geometry, is fundamental to {term}`CAS`. 
To explain why they are essential to all aspects of {term}`CAS`, let's begin with something familiar: a (medical) image:

```{figure} https://cancerquest.org/sites/default/files/2020-04/Ultrasound/IMG_0288.jpg
:label: fig_US_Liver_Tumours
:alt: A ultrasound image of liver with metastatic cancer growths
:align: center
:width: 80%

An ultrasound image of a liver containing metastatic cancer growths, image courtesy [here](https://cancerquest.org/patients/detection-and-diagnosis/ultrasound), accessed on January 6, 2026.
```


## From Pixels to Positions: Why We Need Coordinates

Consider an {term}`US` image of a patient's liver. Displayed on a computer monitor as a {term}`2D' image of different gray scale, different shades of gray represents different tissues types (often highlighted by tissue boundraries). In [](#fig_US_Liver_Tumours) for example, a tumour appears as a darker region within the brighter liver parenchyma. But how does one infer the size and location of a tumour based on an image?

Using a digital computer, a grey-scale image is represented as a **{term}`2D` matrix** of numerical values. Each element in this matrix represents a *pixel*, and the numerical value at each position (pixel) encodes the tissue's appearance in terms of pixel intensity. For example, [](#fig_US_Liver_Tumours) is an image of $245 \times 245$ pixels stored as a matrix:

$$
I = \begin{bmatrix}
I_{0,0} & I_{0,1} & \cdots & I_{0,244} \\
I_{1,0} & I_{1,1} & \cdots & I_{1,244} \\
\vdots & \vdots & \ddots & \vdots \\
I_{244,0} & I_{245,1} & \cdots & I_{244,244}
\end{bmatrix}
$$

where each $I_{i,j}$ represents the intensity value at row $i$ and column $j$. Each pixel in an {term}`US` image is typically represented using a 8-bit of storage (e.g. 1-byte) with the pixel intensity value ranging from $0$ to $255$, where $I_{i,j}=0$ is pure black and $I_{i,j}=255$ is pure white.

```{figure} ./../images/002/fig_image_coordinate.png
:label: fig_US_Liver_Tumours_coord
:alt: A coordinate system assited to an image
:align: center
:width: 80%

A coordinate system assigned to an US image, where the top-left corner is *arbitrary* designated as the origin. A pixel at location $(x,y)$ with an intensity value $v$ is thus referred to as $I(x,y)=v$, image modified based on the image courtesy [here](https://cancerquest.org/patients/detection-and-diagnosis/ultrasound), accessed on January 6, 2026.
```

That is, each pixel in a {term}`2D` image is referred by $(x,y)$ position, which is also the index to the {term}`2D` matrix that is used to store and represent this image in a computer system. The $(x,y)$ location also represents a vector from the origin of the coordinate system $(0,0)$.

### The Challenge: From Image Indices to Physical Space

Suppose a radiologist examines this {term}`US` image and identifies that one of the tumour centre appears at pixel location $(66,110)$ in the image. The logical questions that follow are:
1. **Where is this location in the patient's body**? This matrix indices $(66,110)$ does not indicate anything about the physical location of it with respect to the patient.
1. **What about the physical size of the tumour**? The {term}`2D` matrix, by itself, does not have any information about the physical scale of the image. That is, how do we convert pixel size to a physical unit such as in millimetre?
3. **How do one guide a surgical instrument to this location**? Suppose we want to insert a {term}`RFA` ablation application into this tumour, we need to relate this abstract pixel coordinate system into a physical location that a navigation system can use.

To answer these question requires an understanding of image presentation, coordinate systems, and **transformation** between coordinate systems. In this regard, a review of linear algebra and vector geometry is needed.

### Multi-Channel image and {term}`3D` Volumetric Data

While a {term}`2D` grey-scale image such as {term}`US` or X-ray image can be represented by {term}`2D` matrix in a digital system, color images and volumetric (i.e. {term}`3D`) data requires different representation.

For example, a colour image is typically represented as 3 {term}`2D` images, each {term}`2D` image correspond to a colour channel of red, green, and blue ({term}`RGB`) primary colours. Conceptually, these 3 {term}`2D` images can be stacked on top of each other, forming a {term}`2D` image but each pixel is a {term}`1D` vector of $3$ values (i.e. multi-channel).

```{figure} https://ars.els-cdn.com/content/image/3-s2.0-B9780128230145000077-f03-08-9780128230145.jpg
:label: fig_RGB
:alt: A conceptual representation of a 5x5 RGB colour image
:align: center
:width: 80%

A conceptual representation of a 5x5 RGB colour image, image courtesy [here](https://www.sciencedirect.com/topics/engineering/rgb-image), accessed on January 6, 2026.
```
A {term}`3D` volumetric image data such as {term}`CT` or {term}`MRI` are typically displayed, on a {term}`2D` monitor, as a series of {term}`2D` images:

```{figure} https://images.theconversation.com/files/423640/original/file-20210928-26-3rul6h.jpg?ixlib=rb-4.1.0&q=45&auto=format&w=754&h=503&fit=crop&dpr=1
:label: fig_CT_slices
:alt: CT slices
:align: center
:width: 80%

Sequential CT slices displayed as 2D images, image courtesy [here](https://theconversation.com/50-years-ago-the-first-ct-scan-let-doctors-see-inside-a-living-skull-thanks-to-an-eccentric-engineer-at-the-beatles-record-company-149907), accessed on January 6, 2026.
```

This was mainly done for historical reasons including the lack of computational power to render these volumetric data in {term}`3D` using technique such as <wiki:Volume_rendering>.

A volumetric data is presented digitally as {term}`3D` array in computer where, conceptually, each 2D slice is assigned a $x-y$ coordinate system and sequential images are stacked in the $z-$axis.

```{figure} ./../images/002/fig_3D_volume.png
:label: fig_3D_volume
:alt: A coordinate system assited to a 3D volume
:align: center
:width: 80%

A coordinate system assigned to a 3D volumetric data, where sequential 2D images are assigned a z-coordinate value.
```

In this regard, each **voxel** (i.e. a *volumetric* pixel) is indexed using the $(x,y,z)$ notation.

### Image Fusion and Augmented Reality Visualization

Image fusion and augmented reality visualization requires the alignment of multiple coordinate systems. This is accomplished via **transformation** that maps one coordinate system onto another.

```{figure} https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs11042-023-16515-2/MediaObjects/11042_2023_16515_Fig2_HTML.png?as=webp
:label: fig_Image_Fusion
:alt: Image Fusion
:align: center
:width: 80%

Examples of the common combinations of multimodal medical image fusion (MMIF), image courtesy [here](https://link.springer.com/article/10.1007/s11042-023-16515-2), accessed on January 6, 2026.
```

Categorically, there are three types of transformations:
1. Rigid transformation
    - Represented as a $4 \times 4$ transformation matrix that
        - Rotates, and
        - Translates one coordinate system onto another.
1. Similarity transformation
    - Similar to the rigid translation, but with scaling
    - Also represented as a $4 \times 4$ transformation matrix
    - Scaling can be:
        - Isotropic, same in all 3 directions, or
        - Anisotropic, different in each direction
1. Deformable transformation
    - In some literature, referred to as *elastic* transformation
    - Typically represented as an array ({term}`2D` or {term}`3D`) of deformation fields, or by some parametric function.

For the purpose of this course, we focus on only rigid and similarity transformation.

## Cartesian Coordinate Systems

The key solution is to establish a **<wiki:Cartesian_coordinate_system>**, that specifies each point uniquely by a pair (in {term}`2D`) or a triplet (in {term}`3D`) of real number called *coordinate* that in terms allows use to use vector geometry to address these problems.

A Cartesian coordinate system has
- An **origin**, denoted as $O=(0,0)$ in {term}`2D` or $O=(0,0,0)$ in {term}`3D`,
- **Axes**, a notation of directions, that intersect at the origin. In most of the scenarios we will encounter in this course, these axes are perpenticular to each other, and
- A **scale**. Each increment, i.e. from $(0,0)$ to $(1,0)$, at a coordinate system may correspond to a physical unit. For example, a pixel in an {term}`US` image may occupy a physical space of $1.0mm \times 1.0mm$, but a voxel in a {term}`CT` volume may occupy a physical space of $0.3mm \times 0.3mm \times 0.4mm$. Often, an *anisotropic* scaling is needed to match one coordinate system with another.

## Vector Geometry: Describing Positions and Transformations

In medical imaging and most of the engineering fields, we use a **<wiki:Right-hand_rule>** ({term}`RHR`) to define the orientation of the axes with respect to its origin. That is, when extended, if the thumb points at the first (positive x-) axis, and the index finger points at the second (positive y-) axis, then middle finger points to the third (positive z-) axis.

```{figure} https://upload.wikimedia.org/wikipedia/commons/6/6a/Cartesian-axes-right-hand-rule2.svg
:label: fig_right_hand_rule
:alt: Right hand rule
:align: center
:width: 80%

Right-hand rule, image courtesy of Wikimedia Common [here](https://commons.wikimedia.org/wiki/File:Cartesian-axes-right-hand-rule2.svg), accessed January 9, 2026.
```

This is the opposite of the left-hand rule, which is more commonly employed in Physics.

## Notation for this course:

```{figure} ./../images/002/fig_cartesian.png
:label: fig_cartesian
:alt: Cartesian coordinate system
:align: center
:width: 80%

Righthanded **Cartesian** coordinate system (a.k.a. frame), with $(i,j,k)$ orthonormal bases.
```

We use the following notation:
- Points in capital
- Vectors and location vectors are usually in lower case, often in *italic* and/or **bold**
- $\lvert p \rvert$ is for length of a vector or "absolute value"
- Sometimes, we omit **bold** and/or *italics*
- Sometimes, we use location vectors and points interchangeably
- Sometimes, we use the same letter and font for x,y,z coordinates and labelling the x,y,z axes

Thus, a location vector ***p*** can be expressed by the linear combination of the base vector

$$
p = P = x i + y j + z k
$$

and

$$
length(p) = \lvert p \rvert = sqrt( x^2 + y^2 + z^2)
$$

## Skewed Cartesian Frame

Some CT scanners, such as the Toshiba Asteion 4, has the ability to performed *tilted* scan. The intended use is, as an example, reduce X-ray radiation dose to patient's eye lenses. 

```{figure} ./../images/002/fig_tilted_CT.png
:label: fig_skewed_cartesian
:alt: Skewed Cartesian coordinate system
:align: center
:width: 80%

A Tilted Computed Tomography (CT) machine, aimed to reduce X-ray dose to eye lenses, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```

In this scenario, the base vectors are **no longer** pair-wise orthogonal, however, a point P or location vector $p$ can still be represented by the linear combination of the base vector

$$
p = P = x i + y j + z k
$$

But the length of the vector is no longer the square root of the sums of the squared coordinates:

$$
\lvert p \rvert \ne sqrt( x^2 + y^2 + z^2)
$$

```{figure} ./../images/002/fig_tCT.png
:label: fig_skewed_CT
:alt: Skewed CT slices
:align: center
:width: 80%

A Tilted Computed Tomography (CT) image volume, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```

## Polar Frames

For mathematical convenience, polar frames are often be used to represent coordinate systems.

### Spherical Coordinate System

```{figure} ./../images/002/fig_spherical_coordinate.png
:label: fig_spherical_cartesian
:alt: Spherical  coordinate system
:align: center
:width: 80%

The spherical coordinate system, where the vector is denoted by 2 angles and the length of the vector, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

A vector $\overrightarrow{r}$ with a vector length $r$ is denoted by its length and two angles from $x$- and $z$-axes:

$$
\begin{align}
x & = & r \sin{\theta} \cos{\phi}\\
y & = & r \sin{\theta} \sin{\phi}\\
z & = & r \cos{\theta}\\
\end{align}
$$

A use case for spherical coordinate system is the <wiki:Lars_Leksell> frame:

```{figure} https://coimages.sciencemuseumgroup.org.uk/18/357/medium_1999_0982__0003_.jpg
:label: fig_Leksell
:alt: Laksell Frame
:align: center
:width: 80%

A version of the Leksell Stereotactic frame with angular marking, image courtesy [here](https://collection.sciencemuseumgroup.org.uk/objects/co503283/frame-for-leksell-stereotactic-system), accessed January 8, 2026.
```
commonly used for neurosurgery for inserting a (biopsy/electro) needle:

```{figure} ./../images/002/fig_Leksell_OR
:label: fig_Leksell_OR
:alt: Laksell Frame used in surgery
:align: center
:width: 80%

A Leksell frame used in OR, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```

Because needle is more intuitively represented as a vector (i.e. a point with direction), the use of the spherical coordinate system is more mathematically convenient.

### Cylyndrical Coordinate System

The cylindrical coordinate system is used to describe a point on the surface of a cylinder, where a point is represented by a lenth $\rho$ (radius of the cylinder), an angle $\psi$, and the height $z$:

$$
\begin{align}
x & = & \rho \cos{\psi} \\
y & = & \rho \sin{\psi} \\
z & = & z\\
\end{align}
$$

```{figure} ./../images/002/fig_cylindrical_coordinate.png
:label: fig_cylindrical_coordinate_system
:alt: Cylindrical Coordinate System
:align: center
:width: 80%

The cylindrical coordinate system, where the vector is denoted by 1 angle and a length, and the height, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

One use of the cylindrical coordinate system is the intracavity robot, where an, as an example, a transrectal ultrasound ({term}`TRUS`) is use in surgery.


```{figure} ./../images/002/fig_TRUS_MRI.png
:label: fig_TRUS_MRI
:alt: A transrectal ultrasound in MRI suite
:align: center
:width: 80%

A transrectal ultrasound used an MRI suite, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```
Because the {term}`TRUS` is a cylindrical object, it is more convenient to define a points on its surface (and thereby a direction) using the cylindrical coordinate system.

```{figure} ./../images/002/fig_TRUS.png
:label: fig_TRUS
:alt: A transrectal ultrasound probe
:align: center
:width: 80%

A transrectal ultrasound transducer, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```


## Unit Vector

A **unit** vector is a vector with length one:

```{figure} ./../images/002/fig_unit_vector.png
:label: fig_unit_vector
:alt: A unit vector
:align: center
:width: 80%

A unit vector originated from origin to location $(x,y,z)$.
```
That is,

$$
length(P)=\sqrt{x^2+y^2+z^2} = 1
$$

In [3]:
"""
@author: Prof. Elvis C. S. Chen

January 8, 2026
"""

import math
import numpy as np 
import numpy.matlib

p = np.array([ 1, 0, 0 ])      # This is a ROW vector
p = p.reshape(-1, 1)           # this is a COLUMN vector
p = np.array([ [0],[1],[0] ])  # alternative
print("The 3x1 colume vector:\n", p)
print(p.shape)
print("The length, or norm, of this vector is: ", np.linalg.norm(p))       # Length of the vector can be calculated using numpy

The 3x1 colume vector:
 [[0]
 [1]
 [0]]
(3, 1)
The length, or norm, of this vector is:  1.0


## Scaling of a Vector

A vector can be scaled up (i.e. lengthening) or down (i.e. shortening) by a scalar factor $s$

```{figure} ./../images/002/fig_vector_scaled.png
:label: fig_scaled_vector
:alt: A scaled vector
:align: center
:width: 80%

A vector $P$ beins scaled as $q$.
```

If
- $s>1$, the vector is being lengthened,
- $s<1$, the vector is being shortened,
- $s=1$, nothing happens,
- $s=0$, something is probably wrong,
- $s<0$, the orientation of the vector is changed, in addition to being lengthened/shortened.

In [4]:
# demonstration of scaling of a vector
s = 0.75 # Scaling the vector by a factor of 0.75
q = s * p
print("The original vector p is\n", p, "\nand the scaling factor is:", s, "\n")
print("q is the scaled vector of p: \n", q, "\nwith the norm of the vector being:", np.linalg.norm(q))

The original vector p is
 [[0]
 [1]
 [0]] 
and the scaling factor is: 0.75 

q is the scaled vector of p: 
 [[0.  ]
 [0.75]
 [0.  ]] 
with the norm of the vector being: 0.75


Obviously, scaling of a vector changes its length accordingly.

## Normalizing a Vector

Normalizing a vector meaning to change the vector length to $1$:

```{figure} ./../images/002/fig_normalize_vector.png
:label: fig_normalized_vector
:alt: A normalized vector
:align: center
:width: 80%

A vector $P$ beins normalized as as $q$.
```
In [](#fig_normalized_vector), the vector $q$ is the normalized version of $P$, as the length of $q$ is $1$; both $q$ and $P$ are originated from the origin, pointing in the same direction.

In [5]:
p = np.array([ 3, 4, 5 ])      # This is a ROW vector
p = p.reshape(-1, 1)           # this is a COLUMN vector

q = p/np.linalg.norm(p)
print("The original vector p\n", p, "\nhas a length of", np.linalg.norm(p), "\n")
print("The normalizes vesion q\n", q, "\nhas a length of", np.linalg.norm(q), "\n")

The original vector p
 [[3]
 [4]
 [5]] 
has a length of 7.0710678118654755 

The normalizes vesion q
 [[0.42426407]
 [0.56568542]
 [0.70710678]] 
has a length of 0.9999999999999999 



## Sum of Vectors

Just like scalars, vectors can be added and substracted. Adding two vectors means that you contatenate the end of one vector to the origin of another:

```{figure} ./../images/002/fig_vector_sums.png
:label: fig_vector_sums
:alt: Sum of vectors
:align: center
:width: 80%

Sum of vectors is the same as concatenating the vectors.
```

In [](#fig_vector_sums), the vector $p_3$ is the sum of $p_1$ and $p_2$:

In [6]:
p1 = np.array([ 1, 2, 3 ])
p2 = np.array([ 4, 5, 6 ])
p1 = p1.reshape(-1,1)
p2 = p2.reshape(-1,1)

p3 = p1 + p2

print("the sum of vector 1\n", p1, "\nand vector 2\n", p2, "\nis\n", p3)

the sum of vector 1
 [[1]
 [2]
 [3]] 
and vector 2
 [[4]
 [5]
 [6]] 
is
 [[5]
 [7]
 [9]]


## Distance between two Points

The distance between two points $A$ and $B$ is the length of the vector $\overrightarrow{AB}$ (or $\overrightarrow{BA}$):

```{figure} ./../images/002/fig_points_distance.png
:label: fig_points_distance
:alt: Distance between two points
:align: center
:width: 80%

Distance between two points.
```

In [7]:
print(np.linalg.norm(p2-p1))
print(np.linalg.norm(p1-p2))

5.196152422706632
5.196152422706632


## Cross Product between two Vectors

<wiki:Cross_product> between vectors $a$ and $b$ results in a third vector $c$ that is perpendicular to both $u$ and $v$, with the direction of vector $q$ that obeys the {term}`RHR`. That is, if the right-hand index finger points in the direction of the vector $a$, and the right-hand middle finger points in the direction of the vector $b$, then the thumb points to the direction of $c=a \times b$. Cross product is denoted by the symbol $\times$.

```{figure} https://upload.wikimedia.org/wikipedia/commons/d/d2/Right_hand_rule_cross_product.svg
:label: fig_right_hand_rule_cross
:alt: Right hand rule
:align: center
:width: 80%

Right-hand rule, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Right_hand_rule_cross_product.svg), accessed January 9, 2026.
```

This directionality implies $a \times b \ne b \times a$: cross product is **not** communitive. In fact, the cross product is [anticommutative](https://en.wikipedia.org/wiki/Anticommutative_property):

$$
a \times b = - b \times a
$$

Cross product **is** [distributive](https://en.wikipedia.org/wiki/Distributive_property), however:

$$
a \times (b + c) = a \times b + a \times c
$$

The cross product between $a=(a_1, a_2, a_3)$ and $b=(b_1,b_2,b_3)$ can be expressed as the formal determinant:

$$
\begin{align}
a \times b & = & \begin{vmatrix}
i & j & k \\
a_1 & a_2 & a_3\\
b_1 & b_2 & b_3\\
\end{vmatrix} \\
& = & (a_2 b_3 - a_3 b_2)i + (a_3 b_1 - a_1 b_3)j + (a_1 b_2 - a_3 b_1)k
\end{align}
$$

As such, the magnitude of the resulting vector $c = a \times b$ is:

$$
\left| c\right| = \left| a \right| \left| b \right| \sin{\alpha}
$$
where $\alpha$ is the angle between vectors $a$ and $b$.

Using this property, the cross product can be used to check if two vectors are [parallel](https://en.wikipedia.org/wiki/Parallel_(geometry)) or [antiparallel](https://en.wikipedia.org/wiki/Euclidean_vector#antiparallel): in these scenarios, the cross product results in a zero vector with a length of $0$:

In [8]:
a = np.array([ 1, 0, 0 ])     # this is a row vector
b = np.array([ 1, 0, 0 ])
a = a.reshape(-1,1)           # this is now a column vector
b = b.reshape(-1,1)

c = np.cross(a, b, axis=0)
print("The cross prouct is:\n",c)
print("with the length being:", np.linalg.norm(c))

# what does this line do?
print(np.asin( np.linalg.norm(c) / ((np.linalg.norm(a))*(np.linalg.norm(b))) ) * 180.0 / np.pi )

The cross prouct is:
 [[0]
 [0]
 [0]]
with the length being: 0.0
0.0


You should experiment with the above code, by using different values for $a$ and $b$, and convince yourself that:
1. Indeed the cross product vector $c$ is perpendicular with both $a$ and $b$, and
1. Indeed you can infer the angle between $a$ and $b$

## Orthonormal Basis from Three Points

One utility of cross product often encountered in {term}`CAS` is to define a unique Cartesian coordinate system based on 3 points.

```{figure} ./../images/002/fig_basis_from_points.png
:label: fig_basis_from_3points
:alt: Orthonormal basis from 3 points
:align: center
:width: 80%


A orthonormal basis of $i,j,k$ can be created from 3 points $A$, $B$, and $C$ using vector subtraction and cross product, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

### The axes of the Orthonormal Basis

Given three points $A$, $B$, and $C$, the process of creating a orthonormal basis while keeping the {term}`RHR` are:
1. Create the axis $i$ by $B-A$,
1. Create the axis $k$ by $i \times (C-A)$, and
1. Create the axis $j$ by $k \times i$
1. Normalize each axis 

Note the order of which axis is computed, and try to understand why by visualizing. Normalization of the axes should be performed before taking the cross product to ensure numerical stability.

In [9]:
A = np.array([ 0, 0, 0 ])     # this is a row vector
B = np.array([ 2, 0, 0 ])
C = np.array([ 3, 4, 0 ])
A = A.reshape(-1,1)           # this is now a column vector
B = B.reshape(-1,1)
C = C.reshape(-1,1)

i = (B-A)/np.linalg.norm(B-A)

k = np.cross(i, (C-A)/np.linalg.norm(C-A), axis=0)
k = k/np.linalg.norm(k)

j = np.cross(k, i, axis=0)

print("Basis axis-i, i.e., x:\n", i)
print("Basis axis-j, i.e., y:\n", j)
print("Basis axis-k, i.e., z:\n", k)

Basis axis-i, i.e., x:
 [[1.]
 [0.]
 [0.]]
Basis axis-j, i.e., y:
 [[0.]
 [1.]
 [0.]]
Basis axis-k, i.e., z:
 [[0.]
 [0.]
 [1.]]


### The Origin of the Orthonormal Basis

As a Cartesian coordinate system has an origin, i.e. a common point where all directional axes intersect at, we must define one.

There are two practical choices:
1. Desginate one of the three point as the origin, and associate all axes with it, or
1. use the Center of Gravity ({term}`COG`), i.e. the centroid of the 3 points.

Mathematically, the origin of the newly define Cartesian coordinate system can be anywhere. The {term}`COG` is a reasonable choice, calculated as the unweighted average of the points:

$$
O = \frac{A+B+C}{3}
$$

```{figure} ./../images/002/fig_use_case_ortho_base.png
:label: fig_use_case_basis
:alt: Use case for reference frame
:align: center
:width: 80%

Use case for defining a reference frame including tracking objects, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```
Defining a reference Cartesian coordinate system from three points is used in many techniques in {term}`CAS`; mainly for tracking objects.

```{figure} ./../images/002/fig_reference_frame_from_points.png
:label: fig_reference_frame_from_points
:alt: Reference Frame from points
:align: center
:width: 80%

A reference Cartesian frame $(i,j,k) $defined from points $A$, $B, and $C$, where the origin $O$ is located at the Centre of Gravity, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```


## Area of a Triangle

Visualization in {term}`CAS` uses techniques from computer graphics including [surface wire-frame](https://en.wikipedia.org/wiki/Wire-frame_model) or <wiki:Volume_rendering>. The most common representation of an object with complex geometry is to represent it as a set of connected triangles via a process called <wiki:polygon_triangulation>. In this regard, area of a triangle, and the summation of connected triangles, yields additional information such as the surface area of an organ.

```{figure} ./../images/002/fig_triangulation_represetation.png
:label: fig_triangulated
:alt: Geometrical shapes represented via a series of connected triangles
:align: center
:width: 80%

Use case for triangulation: computing the surface dose of triangulated representation of anatomical structures (e.g. rectum wall) in radiotherapy, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```



The area of a triangle is half of the area of a parallelogram with the same base length and height.


:label: fig_area_triangle
:alt: Area of a triangle
:align: center
:width: 80%

The area of a triangle as half of area of a parallelogram that has the same base length and height, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Triangle.GeometryArea.svg), accessed January 9, 2026.
```
If a triangle is presented by three points $b$, $c$, with the angle $\alpha$ between them, The base of the triangle can be taken as $c$ and the height of the triangle, $h$, is equal to the length of $b$ multiplied by $\sin{\alpha}$:

```{figure} ./../images/002/fig_triangle_vectors.png
:label: fig_area_triangle_vectors
:alt: Area of a triangle
:align: center
:width: 80%

A triangle represented by 2 vectors $b$ and $c$, separated by an angle $\alpha$. The **base** is $c$ and the **height** is $h$.
```

That is, the area of the triangle is calculated as:
$$
\begin{align}
area & = & \frac{1}{2} \cdot base \cdot height \\
& = & \frac{1}{2} \left| c \right| \cdot \left| h \right| \\
& = & \frac{1}{2} \left| c \right| \cdot \left| b \right| \cdot \sin{\alpha} \\
\end{align}
$$

**But** $\left| c \right| \cdot \left| b \right| \cdot \sin{\alpha}$ is the length of the cross product $b \times c$! Thus, the area of a triangle can be computed as:

$$
AREA = \frac{1}{2} \left| b \times c \right|
$$

In [10]:
A = np.array([ 3, 0, 0 ])     # this is a row vector
B = np.array([ 0, 4, 0 ])
A = A.reshape(-1,1)           # this is now a column vector
B = B.reshape(-1,1)

Area = 0.5 * np.linalg.norm( np.cross(A, B, axis=0) )

print( "Area of the triangle is:", Area)

Area of the triangle is: 6.0


## Dot product of Two Vectors

<wiki:Dot_product>, or the inner product, of two vectors, is the sum of the element-wise product. The final value is a scalar and not a vector:

$$
dot(u,v) = u \cdot v = (x_1 x_2 + y_1 y_2 + z_1 z_2) = \left| u \right| \left| v \right| \cos{\alpha}
$$
where $\alpha$ is the angle between these two vectors.

```{figure} https://upload.wikimedia.org/wikipedia/commons/7/76/Inner-product-angle.svg
:label: fig_dot_product
:alt: Dot product between two vectors
:align: center
:width: 80%

Illustration showing how to find the angle between vectors using the dot product, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Inner-product-angle.svg), accessed January 9, 2026.
```

Note the properties of dot product:
- **Commutative**, $a b = b a$
- **Not Associative** (but why?): $(a \cdot b) c \ne a (b \cdot c)$, but
- **Distributive with addition**: $(a+b) \cdot c = a \cdot c + b \cdot c$

It can be trivially shown that the length of a vector is just the square root of the dot product with itself:
$$
length(v) = \sqrt{x^2 + y^2 + z^2} = \sqrt{dot(v,v)}
$$

Because the dot product is related to the cosine of the angle between two vectors, we can use it to evaluate if two vectors are orthogonal with eather other: if their dot product is $0$, implying that $\cos{\alpha}$ is 0, these two vectors must be perpendicular:  

In [11]:
A = np.array([ 3, 0, 0 ])     # this is a row vector
B = np.array([ 0, 4, 0 ])
A = A.reshape(-1,1)           # this is now a column vector
B = B.reshape(-1,1)

# np.dot(A,B) ## won't work as numpy assume row vector. Instead, use this:
print("The dot product is:", A.T@B)

The dot product is: [[0]]


## Angle between Two Vectors

Given two vectors $u$ and $v$ with the angle $\alpha$ in between, we now have 2 ways to calculate the angles:

Via dot product

$$
\begin{align}
\frac{u \cdot v}{\left| u \right| \left| v \right|} & = & \cos{\alpha} \\
\alpha & = & \arccos{\alpha}\\
\end{align}
$$

or via cross product

$$
\begin{align}
\frac{\left| u \times v \right|}{\left| u \right| \left| v \right|} & = & \sin{\alpha} \\
\alpha & = & \arcsin{\alpha}
\end{align}
$$


Given a situation, which one should you use? One recommendation is to consider the slope of the $\sin$ and $\cos$ function and avoid the **flat** area of the curve:

```{figure} https://upload.wikimedia.org/wikipedia/commons/7/71/Sine_cosine_one_period.svg
:label: fig_sine_cosine
:alt: Sine and cosine
:align: center
:width: 80%

Sine and cosine as function of the angle, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Sine_cosine_one_period.svg), accessed January 9, 2026.
```
- Around $0\degree$ use **sine**, i.e. cross product,
- Around $90\degree$ use **cosine**, i.e. dot product

A more robust method is to use both the cross and dot products:

```
atan2( norm( cross(u,v)), dot(u,v))
```

Here is an example:

In [49]:
a = 1e-10                               # a small number
u = 4.0 * np.array([[1],                # a non-unit vector along the x-axis
                    [0],
                    [0]])             
v = 5.0 * np.array([[ math.cos(a) ],    # a non-unit vector different from u
                    [ math.sin(a) ],    # by a very small angle
                      [0]]) 

dotproduct = ((u.T@v)[0])[0]
crossproduct = np.linalg.cross( u, v, axis=0 )
print( "The angle in radian between 2 vectors is:\n", a )
print( "The angle computed using dot product (cosine):\n",
      math.acos( dotproduct / ((np.linalg.norm(u))*(np.linalg.norm(v)))) )
print( "The angle computed using cross product (sine):\n",
      math.asin( np.linalg.norm(crossproduct) / ((np.linalg.norm(u))*(np.linalg.norm(v)))) )
print( "The angle computed using both cross and dot products: \n",
      math.atan2( np.linalg.norm( crossproduct ), dotproduct ))

The angle in radian between 2 vectors is:
 1e-10
The angle computed using dot product (cosine):
 0.0
The angle computed using cross product (sine):
 1e-10
The angle computed using both cross and dot products: 
 1e-10


An use case is to determine the <wiki:Cobb_angle>, a measurement of the bending disorders of the vertebral column, for patients with <wiki:scoliosis> based on an x-ray image:

```{figure} ./../images/002/fig_Cobb.png
:label: fig_Cobb
:alt: Cobb angle to measure scoliosis
:align: center
:width: 80%

Cobb angle is determined from an frontal view of surface-rendered CT volume based on the angle between two vectors, image courtesy of Prof. Gabor Fichtinger of Queen's University, Canada.
```