# Math Primer

## Cartesian Coordinates and Vector Geometry
Linear algebra, particularly Cartesian coordinate systems and vector geometry, is fundamental to {term}`CAS`. 
To explain why they are essential to all aspects of {term}`CAS`, let's begin with something familiar: a (medical) image:

```{figure} https://cancerquest.org/sites/default/files/2020-04/Ultrasound/IMG_0288.jpg
:label: fig_US_Liver_Tumours
:alt: A ultrasound image of liver with metastatic cancer growths
:align: center
:width: 80%

An ultrasound image of a liver containing metastatic cancer growths, image courtesy [here](https://cancerquest.org/patients/detection-and-diagnosis/ultrasound), accessed on January 6, 2026.
```


## From Pixels to Positions: Why We Need Coordinates

Consider an {term}`US` image of a patient's liver. Displayed on a computer monitor as a {term}`2D' image of different gray scale, different shades of gray represents different tissues types (often highlighted by tissue boundraries). In [](#fig_US_Liver_Tumours) for example, a tumour appears as a darker region within the brighter liver parenchyma. But how does one infer the size and location of a tumour based on an image?

Using a digital computer, a grey-scale image is represented as a **{term}`2D` matrix** of numerical values. Each element in this matrix represents a *pixel*, and the numerical value at each position (pixel) encodes the tissue's appearance in terms of pixel intensity. For example, [](#fig_US_Liver_Tumours) is an image of $245 \times 245$ pixels stored as a matrix:

$$
I = \begin{bmatrix}
I_{0,0} & I_{0,1} & \cdots & I_{0,244} \\
I_{1,0} & I_{1,1} & \cdots & I_{1,244} \\
\vdots & \vdots & \ddots & \vdots \\
I_{244,0} & I_{245,1} & \cdots & I_{244,244}
\end{bmatrix}
$$

where each $I_{i,j}$ represents the intensity value at row $i$ and column $j$. Each pixel in an {term}`US` image is typically represented using a 8-bit of storage (e.g. 1-byte) with the pixel intensity value ranging from $0$ to $255$, where $I_{i,j}=0$ is pure black and $I_{i,j}=255$ is pure white.

```{figure} ./../images/002/fig_image_coordinate.png
:label: fig_US_Liver_Tumours_coord
:alt: A coordinate system assited to an image
:align: center
:width: 80%

A coordinate system assigned to an US image, where the top-left corner is *arbitrary* designated as the origin. A pixel at location $(x,y)$ with an intensity value $v$ is thus referred to as $I(x,y)=v$, image modified based on the image courtesy [here](https://cancerquest.org/patients/detection-and-diagnosis/ultrasound), accessed on January 6, 2026.
```

That is, each pixel in a {term}`2D` image is referred by $(x,y)$ position, which is also the index to the {term}`2D` matrix that is used to store and represent this image in a computer system. The $(x,y)$ location also represents a vector from the origin of the coordinate system $(0,0)$.

### The Challenge: From Image Indices to Physical Space

Suppose a radiologist examines this {term}`US` image and identifies that one of the tumour centre appears at pixel location $(66,110)$ in the image. The logical questions that follow are:
1. **Where is this location in the patient's body**? This matrix indices $(66,110)$ does not indicate anything about the physical location of it with respect to the patient.
1. **What about the physical size of the tumour**? The {term}`2D` matrix, by itself, does not have any information about the physical scale of the image. That is, how do we convert pixel size to a physical unit such as in millimetre?
3. **How do one guide a surgical instrument to this location**? Suppose we want to insert a {term}`RFA` ablation application into this tumour, we need to relate this abstract pixel coordinate system into a physical location that a navigation system can use.

To answer these question requires an understanding of image presentation, coordinate systems, and **transformation** between coordinate systems. In this regard, a review of linear algebra and vector geometry is needed.

### Multi-Channel image and {term}`3D` Volumetric Data

While a {term}`2D` grey-scale image such as {term}`US` or X-ray image can be represented by {term}`2D` matrix in a digital system, color images and volumetric (i.e. {term}`3D`) data requires different representation.

For example, a colour image is typically represented as 3 {term}`2D` images, each {term}`2D` image correspond to a colour channel of red, green, and blue ({term}`RGB`) primary colours. Conceptually, these 3 {term}`2D` images can be stacked on top of each other, forming a {term}`2D` image but each pixel is a {term}`1D` vector of $3$ values (i.e. multi-channel).

```{figure} https://ars.els-cdn.com/content/image/3-s2.0-B9780128230145000077-f03-08-9780128230145.jpg
:label: fig_RGB
:alt: A conceptual representation of a 5x5 RGB colour image
:align: center
:width: 80%

A conceptual representation of a 5x5 RGB colour image, image courtesy [here](https://www.sciencedirect.com/topics/engineering/rgb-image), accessed on January 6, 2026.
```
A {term}`3D` volumetric image data such as {term}`CT` or {term}`MRI` are typically displayed, on a {term}`2D` monitor, as a series of {term}`2D` images:

```{figure} https://images.theconversation.com/files/423640/original/file-20210928-26-3rul6h.jpg?ixlib=rb-4.1.0&q=45&auto=format&w=754&h=503&fit=crop&dpr=1
:label: fig_CT_slices
:alt: CT slices
:align: center
:width: 80%

Sequential CT slices displayed as 2D images, image courtesy [here](https://theconversation.com/50-years-ago-the-first-ct-scan-let-doctors-see-inside-a-living-skull-thanks-to-an-eccentric-engineer-at-the-beatles-record-company-149907), accessed on January 6, 2026.
```

This was mainly done for historical reasons including the lack of computational power to render these volumetric data in {term}`3D` using technique such as <wiki:Volume_rendering>.

A volumetric data is presented digitally as {term}`3D` array in computer where, conceptually, each 2D slice is assigned a $x-y$ coordinate system and sequential images are stacked in the $z-$axis.

```{figure} ./../images/002/fig_3D_volume.png
:label: fig_3D_volume
:alt: A coordinate system assited to a 3D volume
:align: center
:width: 80%

A coordinate system assigned to a 3D volumetric data, where sequential 2D images are assigned a z-coordinate value.
```

In this regard, each **voxel** (i.e. a *volumetric* pixel) is indexed using the $(x,y,z)$ notation.

### Image Fusion and Augmented Reality Visualization

Image fusion and augmented reality visualization requires the alignment of multiple coordinate systems. This is accomplished via **transformation** that maps one coordinate system onto another.

```{figure} https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs11042-023-16515-2/MediaObjects/11042_2023_16515_Fig2_HTML.png?as=webp
:label: fig_Image_Fusion
:alt: Image Fusion
:align: center
:width: 80%

Examples of the common combinations of multimodal medical image fusion (MMIF), image courtesy [here](https://link.springer.com/article/10.1007/s11042-023-16515-2), accessed on January 6, 2026.
```

Categorically, there are three types of transformations:
1. Rigid transformation
    - Represented as a $4 \times 4$ transformation matrix that
        - Rotates, and
        - Translates one coordinate system onto another.
1. Similarity transformation
    - Similar to the rigid translation, but with scaling
    - Also represented as a $4 \times 4$ transformation matrix
    - Scaling can be:
        - Isotropic, same in all 3 directions, or
        - Anisotropic, different in each direction
1. Deformable transformation
    - In some literature, referred to as *elastic* transformation
    - Typically represented as an array ({term}`2D` or {term}`3D`) of deformation fields, or by some parametric function.

For the purpose of this course, we focus on only rigid and similarity transformation.

## Cartesian Coordinate Systems

The key solution is to establish a **<wiki:Cartesian_coordinate_system>**, that specifies each point uniquely by a pair (in {term}`2D`) or a triplet (in {term}`3D`) of real number called *coordinate* that in terms allows use to use vector geometry to address these problems.

A Cartesian coordinate system has
- An **origin**, denoted as $O=(0,0)$ in {term}`2D` or $O=(0,0,0)$ in {term}`3D`,
- **Axes**, a notation of directions, that intersect at the origin. In most of the scenarios we will encounter in this course, these axes are perpenticular to each other, and
- A **scale**. Each increment, i.e. from $(0,0)$ to $(1,0)$, at a coordinate system may correspond to a physical unit. For example, a pixel in an {term}`US` image may occupy a physical space of $1.0mm \times 1.0mm$, but a voxel in a {term}`CT` volume may occupy a physical space of $0.3mm \times 0.3mm \times 0.4mm$. Often, an *anisotropic* scaling is needed to match one coordinate system with another.

## Vector Geometry: Describing Positions and Transformations

In medical imaging and most of the engineering fields, we use a **<wiki:Right-hand_rule>** ({term}`RHR`) to define the orientation of the axes with respect to its origin. That is, when extended, if the thumb points at the first (positive x-) axis, and the index finger points at the second (positive y-) axis, then middle finger points to the third (positive z-) axis.

```{figure} https://upload.wikimedia.org/wikipedia/commons/6/6a/Cartesian-axes-right-hand-rule2.svg
:label: fig_right_hand_rule
:alt: Right hand rule
:align: center
:width: 80%

Right-hand rule, image courtesy of Wikimedia Common [here](https://commons.wikimedia.org/wiki/File:Cartesian-axes-right-hand-rule2.svg), accessed January 9, 2026.
```

This is the opposite of the left-hand rule, which is more commonly employed in Physics.

## Notation for this course:

```{figure} ./../images/002/fig_cartesian.png
:label: fig_cartesian
:alt: Cartesian coordinate system
:align: center
:width: 80%

Righthanded **Cartesian** coordinate system (a.k.a. frame), with $(i,j,k)$ orthonormal bases.
```

We use the following notation:
- Points in capital
- Vectors and location vectors are usually in lower case, often in *italic* and/or **bold**
- $\lvert p \rvert$ is for length of a vector or "absolute value"
- Sometimes, we omit **bold** and/or *italics*
- Sometimes, we use location vectors and points interchangeably
- Sometimes, we use the same letter and font for x,y,z coordinates and labelling the x,y,z axes

Thus, a location vector ***p*** can be expressed by the linear combination of the base vector

$$
p = P = x i + y j + z k
$$

and

$$
length(p) = \lvert p \rvert = sqrt( x^2 + y^2 + z^2)
$$

## Skewed Cartesian Frame

Some CT scanners, such as the Toshiba Asteion 4, has the ability to performed *tilted* scan. The intended use is, as an example, reduce X-ray radiation dose to patient's eye lenses. 

```{figure} ./../images/002/fig_tilted_CT.png
:label: fig_skewed_cartesian
:alt: Skewed Cartesian coordinate system
:align: center
:width: 80%

A Tilted Computed Tomography (CT) machine, aimed to reduce X-ray dose to eye lenses, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```

In this scenario, the base vectors are **no longer** pair-wise orthogonal, however, a point P or location vector $p$ can still be represented by the linear combination of the base vector

$$
p = P = x i + y j + z k
$$

But the length of the vector is no longer the square root of the sums of the squared coordinates:

$$
\lvert p \rvert \ne sqrt( x^2 + y^2 + z^2)
$$

```{figure} ./../images/002/fig_tCT.png
:label: fig_skewed_CT
:alt: Skewed CT slices
:align: center
:width: 80%

A Tilted Computed Tomography (CT) image volume, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```

## Polar Frames

For mathematical convenience, polar frames are often be used to represent coordinate systems.

### Spherical Coordinate System

```{figure} ./../images/002/fig_spherical_coordinate.png
:label: fig_spherical_cartesian
:alt: Spherical  coordinate system
:align: center
:width: 80%

The spherical coordinate system, where the vector is denoted by 2 angles and the length of the vector, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

A vector $\overrightarrow{r}$ with a vector length $r$ is denoted by its length and two angles from $x$- and $z$-axes:

$$
\begin{align}
x & = & r \sin{\theta} \cos{\phi}\\
y & = & r \sin{\theta} \sin{\phi}\\
z & = & r \cos{\theta}\\
\end{align}
$$

A use case for spherical coordinate system is the <wiki:Lars_Leksell> frame:

```{figure} https://coimages.sciencemuseumgroup.org.uk/18/357/medium_1999_0982__0003_.jpg
:label: fig_Leksell
:alt: Laksell Frame
:align: center
:width: 80%

A version of the Leksell Stereotactic frame with angular marking, image courtesy [here](https://collection.sciencemuseumgroup.org.uk/objects/co503283/frame-for-leksell-stereotactic-system), accessed January 8, 2026.
```
commonly used for neurosurgery for inserting a (biopsy/electro) needle:

```{figure} ./../images/002/fig_Leksell_OR
:label: fig_Leksell_OR
:alt: Laksell Frame used in surgery
:align: center
:width: 80%

A Leksell frame used in OR, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```

Because needle is more intuitively represented as a vector (i.e. a point with direction), the use of the spherical coordinate system is more mathematically convenient.

### Cylyndrical Coordinate System

The cylindrical coordinate system is used to describe a point on the surface of a cylinder, where a point is represented by a lenth $\rho$ (radius of the cylinder), an angle $\psi$, and the height $z$:

$$
\begin{align}
x & = & \rho \cos{\psi} \\
y & = & \rho \sin{\psi} \\
z & = & z\\
\end{align}
$$

```{figure} ./../images/002/fig_cylindrical_coordinate.png
:label: fig_cylindrical_coordinate_system
:alt: Cylindrical Coordinate System
:align: center
:width: 80%

The cylindrical coordinate system, where the vector is denoted by 1 angle and a length, and the height, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

One use of the cylindrical coordinate system is the intracavity robot, where an, as an example, a transrectal ultrasound ({term}`TRUS`) is use in surgery.


```{figure} ./../images/002/fig_TRUS_MRI.png
:label: fig_TRUS_MRI
:alt: A transrectal ultrasound in MRI suite
:align: center
:width: 80%

A transrectal ultrasound used an MRI suite, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```
Because the {term}`TRUS` is a cylindrical object, it is more convenient to define a points on its surface (and thereby a direction) using the cylindrical coordinate system.

```{figure} ./../images/002/fig_TRUS.png
:label: fig_TRUS
:alt: A transrectal ultrasound probe
:align: center
:width: 80%

A transrectal ultrasound transducer, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada
```


## Unit Vector

A **unit** vector is a vector with length one:

```{figure} ./../images/002/fig_unit_vector.png
:label: fig_unit_vector
:alt: A unit vector
:align: center
:width: 80%

A unit vector originated from origin to location $(x,y,z)$.
```
That is,

$$
length(P)=\sqrt{x^2+y^2+z^2} = 1
$$

In [1]:
"""
@author: Prof. Elvis C. S. Chen

January 8, 2026
"""

import math
import numpy as np 
import numpy.matlib

p = np.array([ 1, 0, 0 ])      # This is a ROW vector
p = p.reshape(-1, 1)           # this is a COLUMN vector
p = np.array([ [0],[1],[0] ])  # alternative
print("The 3x1 colume vector:\n", p)
print(p.shape)
print("The length, or norm, of this vector is: ", np.linalg.norm(p))       # Length of the vector can be calculated using numpy

The 3x1 colume vector:
 [[0]
 [1]
 [0]]
(3, 1)
The length, or norm, of this vector is:  1.0


## Scaling of a Vector

A vector can be scaled up (i.e. lengthening) or down (i.e. shortening) by a scalar factor $s$

```{figure} ./../images/002/fig_vector_scaled.png
:label: fig_scaled_vector
:alt: A scaled vector
:align: center
:width: 80%

A vector $P$ beins scaled as $q$.
```

If
- $s>1$, the vector is being lengthened,
- $s<1$, the vector is being shortened,
- $s=1$, nothing happens,
- $s=0$, something is probably wrong,
- $s<0$, the orientation of the vector is changed, in addition to being lengthened/shortened.

In [2]:
# demonstration of scaling of a vector
s = 0.75 # Scaling the vector by a factor of 0.75
q = s * p
print("The original vector p is\n", p, "\nand the scaling factor is:", s, "\n")
print("q is the scaled vector of p: \n", q, "\nwith the norm of the vector being:", np.linalg.norm(q))

The original vector p is
 [[0]
 [1]
 [0]] 
and the scaling factor is: 0.75 

q is the scaled vector of p: 
 [[0.  ]
 [0.75]
 [0.  ]] 
with the norm of the vector being: 0.75


Obviously, scaling of a vector changes its length accordingly.

## Normalizing a Vector

Normalizing a vector meaning to change the vector length to $1$:

```{figure} ./../images/002/fig_normalize_vector.png
:label: fig_normalized_vector
:alt: A normalized vector
:align: center
:width: 80%

A vector $P$ beins normalized as as $q$.
```
In [](#fig_normalized_vector), the vector $q$ is the normalized version of $P$, as the length of $q$ is $1$; both $q$ and $P$ are originated from the origin, pointing in the same direction.

In [3]:
p = np.array([ 3, 4, 5 ])      # This is a ROW vector
p = p.reshape(-1, 1)           # this is a COLUMN vector

q = p/np.linalg.norm(p)
print("The original vector p\n", p, "\nhas a length of", np.linalg.norm(p), "\n")
print("The normalizes vesion q\n", q, "\nhas a length of", np.linalg.norm(q), "\n")

The original vector p
 [[3]
 [4]
 [5]] 
has a length of 7.0710678118654755 

The normalizes vesion q
 [[0.42426407]
 [0.56568542]
 [0.70710678]] 
has a length of 0.9999999999999999 



## Sum of Vectors

Just like scalars, vectors can be added and substracted. Adding two vectors means that you contatenate the end of one vector to the origin of another:

```{figure} ./../images/002/fig_vector_sums.png
:label: fig_vector_sums
:alt: Sum of vectors
:align: center
:width: 80%

Sum of vectors is the same as concatenating the vectors.
```

In [](#fig_vector_sums), the vector $p_3$ is the sum of $p_1$ and $p_2$:

In [4]:
p1 = np.array([ 1, 2, 3 ])
p2 = np.array([ 4, 5, 6 ])
p1 = p1.reshape(-1,1)
p2 = p2.reshape(-1,1)

p3 = p1 + p2

print("the sum of vector 1\n", p1, "\nand vector 2\n", p2, "\nis\n", p3)

the sum of vector 1
 [[1]
 [2]
 [3]] 
and vector 2
 [[4]
 [5]
 [6]] 
is
 [[5]
 [7]
 [9]]


## Distance between two Points

The distance between two points $A$ and $B$ is the length of the vector $\overrightarrow{AB}$ (or $\overrightarrow{BA}$):

```{figure} ./../images/002/fig_points_distance.png
:label: fig_points_distance
:alt: Distance between two points
:align: center
:width: 80%

Distance between two points.
```

In [5]:
print(np.linalg.norm(p2-p1))
print(np.linalg.norm(p1-p2))

5.196152422706632
5.196152422706632


## Cross Product between two Vectors

<wiki:Cross_product> between vectors $a$ and $b$ results in a third vector $c$ that is perpendicular to both $u$ and $v$, with the direction of vector $q$ that obeys the {term}`RHR`. That is, if the right-hand index finger points in the direction of the vector $a$, and the right-hand middle finger points in the direction of the vector $b$, then the thumb points to the direction of $c=a \times b$. Cross product is denoted by the symbol $\times$.

```{figure} https://upload.wikimedia.org/wikipedia/commons/d/d2/Right_hand_rule_cross_product.svg
:label: fig_right_hand_rule_cross
:alt: Right hand rule
:align: center
:width: 80%

Right-hand rule, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Right_hand_rule_cross_product.svg), accessed January 9, 2026.
```

This directionality implies $a \times b \ne b \times a$: cross product is **not** communitive. In fact, the cross product is [anticommutative](https://en.wikipedia.org/wiki/Anticommutative_property):

$$
a \times b = - b \times a
$$

Cross product **is** [distributive](https://en.wikipedia.org/wiki/Distributive_property), however:

$$
a \times (b + c) = a \times b + a \times c
$$

The cross product between $a=(a_1, a_2, a_3)$ and $b=(b_1,b_2,b_3)$ can be expressed as the formal determinant:

$$
\begin{align}
a \times b & = & \begin{vmatrix}
i & j & k \\
a_1 & a_2 & a_3\\
b_1 & b_2 & b_3\\
\end{vmatrix} \\
& = & (a_2 b_3 - a_3 b_2)i + (a_3 b_1 - a_1 b_3)j + (a_1 b_2 - a_3 b_1)k
\end{align}
$$

As such, the magnitude of the resulting vector $c = a \times b$ is:

$$
\left| c\right| = \left| a \right| \left| b \right| \sin{\alpha}
$$
where $\alpha$ is the angle between vectors $a$ and $b$.

Using this property, the cross product can be used to check if two vectors are [parallel](https://en.wikipedia.org/wiki/Parallel_(geometry)) or [antiparallel](https://en.wikipedia.org/wiki/Euclidean_vector#antiparallel): in these scenarios, the cross product results in a zero vector with a length of $0$:

In [6]:
a = np.array([ 1, 0, 0 ])     # this is a row vector
b = np.array([ 1, 0, 0 ])
a = a.reshape(-1,1)           # this is now a column vector
b = b.reshape(-1,1)

c = np.cross(a, b, axis=0)
print("The cross prouct is:\n",c)
print("with the length being:", np.linalg.norm(c))

# what does this line do?
print(np.asin( np.linalg.norm(c) / ((np.linalg.norm(a))*(np.linalg.norm(b))) ) * 180.0 / np.pi )

The cross prouct is:
 [[0]
 [0]
 [0]]
with the length being: 0.0
0.0


You should experiment with the above code, by using different values for $a$ and $b$, and convince yourself that:
1. Indeed the cross product vector $c$ is perpendicular with both $a$ and $b$, and
1. Indeed you can infer the angle between $a$ and $b$

## Orthonormal Basis from Three Points

One utility of cross product often encountered in {term}`CAS` is to define a unique Cartesian coordinate system based on 3 points.

```{figure} ./../images/002/fig_basis_from_points.png
:label: fig_basis_from_3points
:alt: Orthonormal basis from 3 points
:align: center
:width: 80%


A orthonormal basis of $i,j,k$ can be created from 3 points $A$, $B$, and $C$ using vector subtraction and cross product, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

### The axes of the Orthonormal Basis

Given three points $A$, $B$, and $C$, the process of creating a orthonormal basis while keeping the {term}`RHR` are:
1. Create the axis $i$ by $B-A$,
1. Create the axis $k$ by $i \times (C-A)$, and
1. Create the axis $j$ by $k \times i$
1. Normalize each axis 

Note the order of which axis is computed, and try to understand why by visualizing. Normalization of the axes should be performed before taking the cross product to ensure numerical stability.

In [7]:
A = np.array([ 0, 0, 0 ])     # this is a row vector
B = np.array([ 2, 0, 0 ])
C = np.array([ 3, 4, 0 ])
A = A.reshape(-1,1)           # this is now a column vector
B = B.reshape(-1,1)
C = C.reshape(-1,1)

i = (B-A)/np.linalg.norm(B-A)

k = np.cross(i, (C-A)/np.linalg.norm(C-A), axis=0)
k = k/np.linalg.norm(k)

j = np.cross(k, i, axis=0)

print("Basis axis-i, i.e., x:\n", i)
print("Basis axis-j, i.e., y:\n", j)
print("Basis axis-k, i.e., z:\n", k)

Basis axis-i, i.e., x:
 [[1.]
 [0.]
 [0.]]
Basis axis-j, i.e., y:
 [[0.]
 [1.]
 [0.]]
Basis axis-k, i.e., z:
 [[0.]
 [0.]
 [1.]]


### The Origin of the Orthonormal Basis

As a Cartesian coordinate system has an origin, i.e. a common point where all directional axes intersect at, we must define one.

There are two practical choices:
1. Desginate one of the three point as the origin, and associate all axes with it, or
1. use the Center of Gravity ({term}`COG`), i.e. the centroid of the 3 points.

Mathematically, the origin of the newly define Cartesian coordinate system can be anywhere. The {term}`COG` is a reasonable choice, calculated as the unweighted average of the points:

$$
O = \frac{A+B+C}{3}
$$

```{figure} ./../images/002/fig_use_case_ortho_base.png
:label: fig_use_case_basis
:alt: Use case for reference frame
:align: center
:width: 80%

Use case for defining a reference frame including tracking objects, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```
Defining a reference Cartesian coordinate system from three points is used in many techniques in {term}`CAS`; mainly for tracking objects.

```{figure} ./../images/002/fig_reference_frame_from_points.png
:label: fig_reference_frame_from_points
:alt: Reference Frame from points
:align: center
:width: 80%

A reference Cartesian frame $(i,j,k) $defined from points $A$, $B, and $C$, where the origin $O$ is located at the Centre of Gravity, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```


## Area of a Triangle

Visualization in {term}`CAS` uses techniques from computer graphics including [surface wire-frame](https://en.wikipedia.org/wiki/Wire-frame_model) or <wiki:Volume_rendering>. The most common representation of an object with complex geometry is to represent it as a set of connected triangles via a process called <wiki:polygon_triangulation>. In this regard, area of a triangle, and the summation of connected triangles, yields additional information such as the surface area of an organ.

```{figure} ./../images/002/fig_triangulation_represetation.png
:label: fig_triangulated
:alt: Geometrical shapes represented via a series of connected triangles
:align: center
:width: 80%

Use case for triangulation: computing the surface dose of triangulated representation of anatomical structures (e.g. rectum wall) in radiotherapy, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```



The area of a triangle is half of the area of a parallelogram with the same base length and height.


:label: fig_area_triangle
:alt: Area of a triangle
:align: center
:width: 80%

The area of a triangle as half of area of a parallelogram that has the same base length and height, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Triangle.GeometryArea.svg), accessed January 9, 2026.
```
If a triangle is presented by three points $b$, $c$, with the angle $\alpha$ between them, The base of the triangle can be taken as $c$ and the height of the triangle, $h$, is equal to the length of $b$ multiplied by $\sin{\alpha}$:

```{figure} ./../images/002/fig_triangle_vectors.png
:label: fig_area_triangle_vectors
:alt: Area of a triangle
:align: center
:width: 80%

A triangle represented by 2 vectors $b$ and $c$, separated by an angle $\alpha$. The **base** is $c$ and the **height** is $h$.
```

That is, the area of the triangle is calculated as:
$$
\begin{align}
area & = & \frac{1}{2} \cdot base \cdot height \\
& = & \frac{1}{2} \left| c \right| \cdot \left| h \right| \\
& = & \frac{1}{2} \left| c \right| \cdot \left| b \right| \cdot \sin{\alpha} \\
\end{align}
$$

**But** $\left| c \right| \cdot \left| b \right| \cdot \sin{\alpha}$ is the length of the cross product $b \times c$! Thus, the area of a triangle can be computed as:

$$
AREA = \frac{1}{2} \left| b \times c \right|
$$

In [8]:
A = np.array([ 3, 0, 0 ])     # this is a row vector
B = np.array([ 0, 4, 0 ])
A = A.reshape(-1,1)           # this is now a column vector
B = B.reshape(-1,1)

Area = 0.5 * np.linalg.norm( np.cross(A, B, axis=0) )

print( "Area of the triangle is:", Area)

Area of the triangle is: 6.0


## Dot product of Two Vectors

<wiki:Dot_product>, or the inner product, of two vectors, is the sum of the element-wise product. The final value is a scalar and not a vector:

$$
dot(u,v) = u \cdot v = (x_1 x_2 + y_1 y_2 + z_1 z_2) = \left| u \right| \left| v \right| \cos{\alpha}
$$
where $\alpha$ is the angle between these two vectors.

```{figure} https://upload.wikimedia.org/wikipedia/commons/7/76/Inner-product-angle.svg
:label: fig_dot_product
:alt: Dot product between two vectors
:align: center
:width: 80%

Illustration showing how to find the angle between vectors using the dot product, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Inner-product-angle.svg), accessed January 9, 2026.
```

Note the properties of dot product:
- **Commutative**, $a b = b a$
- **Not Associative** (but why?): $(a \cdot b) c \ne a (b \cdot c)$, but
- **Distributive with addition**: $(a+b) \cdot c = a \cdot c + b \cdot c$

It can be trivially shown that the length of a vector is just the square root of the dot product with itself:
$$
length(v) = \sqrt{x^2 + y^2 + z^2} = \sqrt{dot(v,v)}
$$

Because the dot product is related to the cosine of the angle between two vectors, we can use it to evaluate if two vectors are orthogonal with eather other: if their dot product is $0$, implying that $\cos{\alpha}$ is 0, these two vectors must be perpendicular:  

In [9]:
A = np.array([ 3, 0, 0 ])     # this is a row vector
B = np.array([ 0, 4, 0 ])
A = A.reshape(-1,1)           # this is now a column vector
B = B.reshape(-1,1)

# np.dot(A,B) ## won't work as numpy assume row vector. Instead, use this:
print("The dot product is:", A.T@B)

The dot product is: [[0]]


## Angle between Two Vectors

Given two vectors $u$ and $v$ with the angle $\alpha$ in between, we now have 2 ways to calculate the angles:

Via dot product

$$
\begin{align}
\frac{u \cdot v}{\left| u \right| \left| v \right|} & = & \cos{\alpha} \\
\alpha & = & \arccos{\alpha}\\
\end{align}
$$

or via cross product

$$
\begin{align}
\frac{\left| u \times v \right|}{\left| u \right| \left| v \right|} & = & \sin{\alpha} \\
\alpha & = & \arcsin{\alpha}
\end{align}
$$


Given a situation, which one should you use? One recommendation is to consider the slope of the $\sin$ and $\cos$ function and avoid the **flat** area of the curve:

```{figure} https://upload.wikimedia.org/wikipedia/commons/7/71/Sine_cosine_one_period.svg
:label: fig_sine_cosine
:alt: Sine and cosine
:align: center
:width: 80%

Sine and cosine as function of the angle, image courtesy of Wikimedia Commons [here](https://commons.wikimedia.org/wiki/File:Sine_cosine_one_period.svg), accessed January 9, 2026.
```
- Around $0\degree$ use **sine**, i.e. cross product,
- Around $90\degree$ use **cosine**, i.e. dot product

A more robust method is to use both the cross and dot products:

```
atan2( norm( cross(u,v)), dot(u,v))
```

Here is an example:

In [10]:
a = 1e-10                               # a small number
u = 4.0 * np.array([[1],                # a non-unit vector along the x-axis
                    [0],
                    [0]])             
v = 5.0 * np.array([[ math.cos(a) ],    # a non-unit vector different from u
                    [ math.sin(a) ],    # by a very small angle
                      [0]]) 

dotproduct = ((u.T@v)[0])[0]
crossproduct = np.linalg.cross( u, v, axis=0 )
print( "The angle in radian between 2 vectors is:\n", a )
print( "The angle computed using dot product (cosine):\n",
      math.acos( dotproduct / ((np.linalg.norm(u))*(np.linalg.norm(v)))) )
print( "The angle computed using cross product (sine):\n",
      math.asin( np.linalg.norm(crossproduct) / ((np.linalg.norm(u))*(np.linalg.norm(v)))) )
print( "The angle computed using both cross and dot products: \n",
      math.atan2( np.linalg.norm( crossproduct ), dotproduct ))

The angle in radian between 2 vectors is:
 1e-10
The angle computed using dot product (cosine):
 0.0
The angle computed using cross product (sine):
 1e-10
The angle computed using both cross and dot products: 
 1e-10


An use case is to determine the <wiki:Cobb_angle>, a measurement of the bending disorders of the vertebral column, for patients with <wiki:scoliosis> based on an x-ray image:

```{figure} ./../images/002/fig_Cobb.png
:label: fig_Cobb
:alt: Cobb angle to measure scoliosis
:align: center
:width: 80%

Cobb angle is determined from an frontal view of surface-rendered CT volume based on the angle between two vectors, image courtesy of Prof. Gabor Fichtinger of Queen's University, Canada.
```

## Vector Representation of a Line

There are many ways to represent a line. In fact, the appropriate representation often depends on mathematical convenience and the *definition* of a line. In {term}`CAS`, a line could mean
- an *oriented* line: a line with a point on the line (i.e. the *origin*) and a direction (often represented by a unit vector)
- a line *segment*: a line with length
    - can be represented by the two end points of the line segment, or
    - can be represented by one of the end point plus a vector of the known length
 
```{figure} ./../images/002/fig_line.png
:label: fig_line
:alt: Line representation
:align: center
:width: 80%

A line can be presented by a fixed point $P$, a unit dictional vector $v$, and a parameter $t$, where another point $L$ on the lie is $L=P+t \cdot v$.
```

### Parameterized Line

```{figure} ./../images/002/fig_line_parameterized.png
:label: fig_line_parameterized
:alt: Parameterized Line representation
:align: center
:width: 80%

A line can be presented by a fixed point $P$, a unit dictional vector $v$, and a parameter $t$, where another point $L$ on the lie is $L=P+t \cdot v$.
```

Let $P$ be a point on a line, and a unit vector $v$ be the direction (orientation) of the line. Another point $L$ on the line can be parameterized as:

$$
L = P + t \cdot v
$$

where $t$ is a scalar, effectively specifying how far $L$ is from $P$. Specifically, $L$ is calculated as

$$
\begin{align}
L_x & = & P_x + t * v_x\\
L_y & = & P_y + t * v_y\\
L_z & = & P_z + t * v_z\\
\end{align}
$$

The orientation vector $v$ **does not need** to be a unit vector, but mathematically convenient if it is. The range of $t$ specify the type of the line:
- **Infinite line**: $t \in \{ -\infty, \infty \}$
- **Ray**: $t \in \{ 0, \infty \}$
- **Line Segment**: $t \in \{ t_{min}, t_{max} \}$

To understand what the parameterizing parameter $t$ is, let's rearrange the equation of the line:

$$
\begin{align}
L & = & P + t \cdot v\\
L-P & = & t \cdot v \\
\left| L - P \right| & = & t \left| v \right|\\
\end{align}
$$

Because $\left| v \right| = 1$, i.e. $v$ was normalized, then

$$
\left| L - P \right| = t
$$

That is, if $v$ is a unit vector, the parameter $t$ measures the distance between the fixed point $P$ and the running point $L$.

In [11]:
P = np.array([[0],          # a fixed point on the line
              [0],
              [0]])  
v = np.array([[1],          # orientation of the line as a unit vector
              [0],
              [0]])
t = 3.0                     # line parameterization
L = P + t * v               # another point on the line
print( L )

[[3.]
 [0.]
 [0.]]


### Line Defined by Two Points

Give two points $P$ and $L$ on a line, the orientation of the line can be determined by

$$
dir = L-P
$$

The orientation **unit** vector $v$ is

$$
v = \frac{dir}{\left| dir \right|}
$$

That is, the orientaiton of the line is determined by substracting one point from another; the order of which is important as it determines the direction of the line. The orientation vector is normalized for mathematical convenience.

In [12]:
P = np.array([[0],          # a fixed point on the line
              [0],
              [0]])  
L = np.array([[3],          # another point on the same line
              [0],
              [0]])
dir = L-P                   # orientation of the line
v = dir/np.linalg.norm(dir) # normalized orientation, i.e. a unit vector
print(v)

[[1.]
 [0.]
 [0.]]


## Distance of a Point from a Line

The distance between a point $A$ and a line $L$ is defined as the **shortest** distance beween $A$ to any points on $L$. Suppose a line is represented by the fixed point on the line $P$ and a **unit** orientation vector $v$. The length $c=\left| \overrightarrow{AP} \right|$ is the distance between point $A$ and $P$ and is the length of the hypotenuse of a right-angle triangle. The projection of $\overrightarrow{AP}$ onto $L$ is the adjacent of the right-angle triangle, with the angle denoted as $\alpha$. The distance between the point $A$ and line $L$ is the length of the opposite of the right-angle triangle.

```{figure} ./../images/002/fig_distance_point_line.png
:label: fig_line_distance_point
:alt: Distance between a point and a line
:align: center
:width: 80%

The distance between a point $A$ and line $L$ can be calculated based a triangle being formed.
```
Using this right-angle triangle, one can calculate the distance $d$ using:

$$
\begin{align}
c & = & \left| A - P \right| \\
a & = & \left| v \cdot (A-P) \right| \\
d^2 & = & c^2 - a^2\\
d^2 & = & (c+a)(c-a)\\
d & = & \sqrt{(c+a)(c-a)}\\
\end{align}
$$

In [13]:
P = np.array([[0],              # a fixed point on the line
              [0],
              [0]])
v = np.array([[1],              # a unit vector representing the orientation of the line
              [0],
              [0]])
A = np.array([[3],              # a point NOT on the line
              [4],
              [0]])

c = np.linalg.norm( A-P )
a = np.linalg.norm( v.T@(A-P) )
d = math.sqrt( (c+a)*(c-a) )    # just a more efficient way of calculating c*c-a*a
print(d)

4.0


This formulation calculates the distance between a point $A$ and an line $L$ **without** knowing which point on the $L$ is the closest to $A$. However, since we know $a$, the length of the adjacent of the right-angle triangle, we can determine which point on $L$ is closest to A:

$$
Q = P+a*v
$$

In [14]:
Q = P + a*v                     # Q is a point on line L that is closest to point A
print( Q )
print( np.linalg.norm(A-Q))     # The length of the vector AQ

[[3.]
 [0.]
 [0.]]
4.0


A use case in {term}`CAS`: suppose we want to insert a biopsy needle (a line) into the center of the prostate (a point) to take a sample; one may wish to know how far away the biopsy needle is to the intented target.

```{figure} ./../images/002/fig_prostate_US.png
:label: fig_prostate_ultrasound
:alt: Use case for the distance between a point and a line
:align: center
:width: 80%

Screen capture in ultrasound-guided prostate biopsy navigation. Computing the needle placement error as the distance between the planned target (a point) and the actual needle path observed in ultrasound (a line), image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

## Plane

A plane is represented by a point $A$ on the plane and the surface normal $n$ of the plane. For mathematical convenience, the normal of the plane $n$ is normalized with a length of $1$.

```{figure} ./../images/002/fig_plane.png
:label: fig_plane
:alt: Distance between a point and a line
:align: center
:width: 80%

The distance between a point $A$ and line $L$ can be calculated based a triangle being formed.
```

Given 3 points $A$, $B$, and $C$ on a plane, the plane normal vector $n$ can be computed by their cross product:

$$
n = normalize( (B-A) \times (C-A) )
$$

```{figure} ./../images/002/fig_plane_3points.png
:label: fig_plane_3points
:alt: Distance between a point and a line
:align: center
:width: 80%

The distance between a point $A$ and line $L$ can be calculated based a triangle being formed.
```

In [15]:
A = np.array([[0],              # a point on the plane
              [0],
              [0]])
B = np.array([[1],              # a point on the plane
              [0],
              [0]])
C = np.array([[0],              # a point on the plane
              [1],
              [0]])

dir = np.linalg.cross( (B-A), (C-A), axis=0 )
n = dir/np.linalg.norm(dir)
print( "plane normal vector is:\n", n)

plane normal vector is:
 [[0.]
 [0.]
 [1.]]


### Distance from a Plane
The distance between a point $P$ from a plane $(n, A)$, where $n$ is a unit vector specifying the normal of the plane, and $A$ is a point on the plane, is the length of the projection of $\overrightarrow{AP}$ to the surface normal $n$:

$$
D = (L-A) \cdot n
$$

```{figure} ./../images/002/fig_plane_distance_point.png
:label: fig_plane_distance
:alt: Distance between a plane and a point
:align: center
:width: 80%

The distance between a point $P$ and plane $(n, A)$ can be calculated as a dot product.
```

Notice the plane normal $n$ has a direction:
- if $d>0$, then $P$ is above the plane,
- if $d<0$, then $P$ is below the plane,
- if $d=0$, then $P$ is on the plane.

In [16]:
A = np.array([[0],                 # a point on the plane
              [0],
              [0]])
n = np.array([[0],                 # plane normal
              [0],
              [1]])
P = np.array([[3],                 # a point 
              [4],
              [5]])

d = (n.T@(P-A))[0][0]
print("The distance is:", d)

The distance is: 5


### Intersection of Line and Plane

The intersection between a line, $L=P+vt$, and a plane, $(n,A)$ can be calculated as the following.

```{figure} ./../images/002/fig_line_plane.png
:label: fig_line_plane
:alt: Line and plane intersection
:align: center
:width: 80%

The intersection between a parameterized line $P+vt$ to a plane $(n,A)$.
```

Assuming the line is parameterized with $t$:

$$
L=P+v t
$$ (label_eqn_line)

When $L$ intersects with the plane, i.e. $L$ is **on** the plane, then

$$
(L-A) \cdot n = 0
$$ (label_eqn_plane)

Substitute Eqn.[](#label_eqn_line) into Eqn.[](#label_eqn_plane):

$$
(P+v t -A) \cdot n = 0
$$

Using the distributive property of <wiki:dot_product>, one obtains:

$$
(P-A)\cdot n + (v \cdot n) t = 0
$$

Rearrange for $t$:

$$
t = \frac{(A-P) \cdot n}{ v \cdot n}
$$

Substitute $t$ back to Eqn.[](#Label_eqn_line) to obtain the intersection point $L=P+v t$.

One of the use case involves the use of <wiki:X-ray> or <wiki:Fluoroscopy> where X-ray, originated from a point source, is treated as a line, and the image detector is the plane.

```{figure} ./../images/002/fig_line_plane_use.png
:label: fig_line_plane_use
:alt: Use case for line and plane intersection
:align: center
:width: 80%

The intersection between an X-ray to the detector as a use case for calculating the intersection between a line and a plane, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```


## Intersection of Lines in 3D

Intersection of lines in {term}`3D` is common in motion analysis, often involved the usa of stereo camera of [bi-plane fluoroscopy](https://en.wikipedia.org/wiki/X-ray_motion_analysis). In [](#fig_bi_plane_xray), the <wiki:X-ray> source is treated as a <wiki:Pinhole_camera>, and the principle of <wiki:triangulation> is used to localize an object.

```{figure} ./../images/002/fig_bi_plane_xray.png
:label: fig_bi_plane_xray
:alt: Bi-plane X-ray
:align: center
:width: 80%

Biplane X-ray target reconstruction, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

Let two lines be represented parametrically:

$$
\begin{align}
L_1 & = & P_1 + t_1 v_1\\
L_2 & = & P_2 + t_2 v_2\\
\end{align}
$$

Expanding for each $(x,y,z)$ components, one obtains:

$$
\begin{align}
L_{1x} & = & P_{1x} + t_{1} v_{1x}\\
L_{1y} & = & P_{1y} + t_{1} v_{1y}\\
L_{1z} & = & P_{1z} + t_{1} v_{1z}\\
\end{align}
$$

and

$$
\begin{align}
L_{2x} & = & P_{2x} + t_{2} v_{2x}\\
L_{2y} & = & P_{2y} + t_{2} v_{2y}\\
L_{2z} & = & P_{2z} + t_{2} v_{2z}\\
\end{align}
$$

where

$$
\begin{align}
t_1 & \in & (-\infty, \infty) \
t_2 & \in & (-\infty, \infty) \\
\end{align}
$$


If lines intersect with each other, they share a common point in space. That is,

$$
\begin{align}
L_1 & = & L_2 \\
L_1 - L_2 & = & 0
\end{align}
$$ 

for some $L_1$ and $L_2$, and

$$
\begin{align}
P_{1x} - P_{2x} + t_1 v_{1x} - t_2 v_{2x} & = & 0\\
P_{1y} - P_{2y} + t_1 v_{1y} - t_2 v_{2y} & = & 0\\
P_{1z} - P_{2z} + t_1 v_{1z} - t_2 v_{2z} & = & 0\\
\end{align}
$$ 

There $t_1$ and $t_2$ are unknown. You should note that these are $3$ equations with $2$ unknowns, thus, **in general**, *two lines do not intersect in {term}`3D`*.

```{figure} ./../images/002/fig_2_lines_intersection.png
:label: fig_2_lines_intersection
:alt: Intersection of 2 lines in 3D.
:align: center
:width: 80%

Intersection of 2 lines in {term}`3D`.
```

In other words, $2$ lines intersect with each other if one of these three equations cancels out. That is, if one of the equations can be expressed as a linear combination of the other two: **they lie on a common plane**. However, this does not happen in general, either because two lines in fact do not intersect with each other, or they do but numerically the equations above cannot be satisfied due to digital representation.

**But** we can in fact calculate a "symbolic intersection": find the shortest distance between two lines and the midway point.


The **symbolic** intersection point $M$ is a point that is equal distance from both lines. It can be computed in 3 steps:
1. Find a line $L_3$ that is perpendicular to both lines,
1. Find the intersection of line $L_3$ with both lines $L_1$ and $L_2$, and
1. Find the middle point $M$ on $L_3$

```{figure} ./../images/002/fig_line_intersection_symbolic.png
:label: fig_symbolic_lines_intersection
:alt: Symbolic intersection of 2 lines in 3D.
:align: center
:width: 80%

Symbolic intersection, $M$, of 2 lines in {term}`3D`. $v_3$ is perpendicular to both $v_1$ and $v_2$ and $M$ is mid-way from $L_1$ and $L_2$ with a distance $\frac{d}{2}$.
```

The distance between the mid-way point $M$ is denoted as the Residual Eerror Metric ({term}`REM`), which is $\frac{d}{2}$, and $d$ is the distance between lines $L_1$ and $L_2$.


Line 3 $L_3=P_3 + t_3 v_3$ is perpendicular to the other two lines, thus, its directional vector $v_3$ can be computed as the cross product of the other two directional vectors:

$$
v_3 = normalize( v_1 \times v_2 )
$$

The length of $v_3$ is normalized to be $1$, again, for mathematical convenience.

```{figure} ./../images/002/fig_2_lines_intersection_step1.png
:label: fig_symbolic_lines_intersection_step1
:alt: Symbolic intersection of 2 lines in 3D.
:align: center
:width: 80%

Symbolic intersection, $M$, of 2 lines in {term}`3D`. $v_3$ is perpendicular to both $v_1$ and $v_2$ and $M$ is mid-way from $L_1$ and $L_2$ with a distance $\frac{d}{2}$.
```

As such, the fixed point $P_3$ and the parameterized point $L_3$ on this line can be designate as 

$$
P_3 = L_2 
$$ (label_eqn_P3)

$$
L_3 = L_1 
$$ (label_eqn_L3)

Because the equations for all three lines are:

$$
L_1 =  P_1 + t_1 v_1
$$ (label_eqn_L1)

$$
L_2  =  P_2 + t_2 v_2
$$ (label_eqn_L2)

$$
L_3  =  P_3 + t_3 v_3
$$(label_eqn_L32)

Substituting Eqn.[](#Label_eqn_P3) and Eqn.[](#Label_eqn_L3) into Eqn.[](#Label_eqn_L32) yields:

$$
\begin{align}
L_3 & = & P_3 + t_3 v_3 \\
P_1 + t_1 v_1 & = & P_2 + t_2 v_2 + t_3 v_3
\end{align}
$$

After rearrangement:

$$
P_1 - P_2 = - t_1 v_1 + t_2 v_2 + t_3 v_3
$$

and expanding it to each of the 3 dimensions:


$$
\begin{align}
P_{1x} - P_{2x} & = & - t_1 v_{1x} + t_2 v_{2x} + t_3 v_{3x} \\
P_{1y} - P_{2z} & = & - t_1 v_{1y} + t_2 v_{2y} + t_3 v_{3y} \\
P_{1z} - P_{2z} & = & - t_1 v_{1z} + t_2 v_{2z} + t_3 v_{3z} \\
\end{align}
$$

where $t_1$, $t_2$ and $t_3$ are unknown. Now there are 3 equations and 3 unknown, implying that a unique solution does exist.

These equations can be represented using matrices:

$$
\begin{bmatrix} 
P_{1x} - P_{2x} \\
P_{1y} - P_{2y} \\
P_{1z} - P_{2z}
\end{bmatrix} =
\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}
\begin{bmatrix} 
t_{1} \\
t_{2} \\
t_{3} \\
\end{bmatrix}
$$

The unknown $t_1$, $t_2$ and $t_3$ can be solved using
- <wiki:Gaussian_elimination>
- Algebraic substitution, or
- Matrix inversion (shown below)


$$
\begin{align}

\begin{bmatrix} 
P_{1x} - P_{2x} \\
P_{1y} - P_{2y} \\
P_{1z} - P_{2z}
\end{bmatrix} & = &
\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}
\begin{bmatrix} 
t_{1} \\
t_{2} \\
t_{3} \\
\end{bmatrix} \\
\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}^{-1}
\begin{bmatrix} 
P_{1x} - P_{2x} \\
P_{1y} - P_{2y} \\
P_{1z} - P_{2z}
\end{bmatrix} & = &
\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}^{-1}

\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}
\begin{bmatrix} 
t_{1} \\
t_{2} \\
t_{3} \\
\end{bmatrix} \\
\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}^{-1}
\begin{bmatrix} 
P_{1x} - P_{2x} \\
P_{1y} - P_{2y} \\
P_{1z} - P_{2z}
\end{bmatrix} & = &
I
\begin{bmatrix} 
t_{1} \\
t_{2} \\
t_{3} \\
\end{bmatrix}\\
\begin{bmatrix}
- v_{1x} & v_{2x} & v_{3x}\\
- v_{1y} & v_{2y} & v_{3y}\\
- v_{1z} & v_{2z} & v_{3z}\\
\end{bmatrix}^{-1}
\begin{bmatrix} 
P_{1x} - P_{2x} \\
P_{1y} - P_{2y} \\
P_{1z} - P_{2z}
\end{bmatrix} & = &
\begin{bmatrix} 
t_{1} \\
t_{2} \\
t_{3} \\
\end{bmatrix}
\end{align} 
$$

Once $t_1$, $t_2$, and $t_3$ are calculated, substitute them back to

$$
\begin{align}
L_1 & = & P_1 + t_1 v_1 \\
L_2 & = & P_2 + t_2 v_2
\end{align}
$$ 

to solve for $L_1$ and $L_2$. Note that

$$
t_3 = \left| L_1 - L_2 \right|
$$

and

$$
M = \frac{L_1+L_2}{2}
$$

The {term}`REM`, which is the distance of $M$ from either $L_1$ or $L_2$ is:

$$
REM = \left| L_1 - M \right| = \left| L_2 - M \right| = \frac{t_3}{2}
$$

In [69]:
P1 = np.array([[0],                 # a point on z=0 plane
              [0],
              [0]])
v1 = np.array([[1],                 # line orientation +x
              [0],
              [0]])
P2 = np.array([[0],                 # a point on z=5 plane
              [0],
              [5]])
v2 = np.array([[0],                 # line orientation +y
              [1],
              [0]])

v3 = np.linalg.cross( v1, v2, axis=0 )


V = np.zeros((3,3))                 # construct the 3x3 matrix
V[:,0] = -1*v1.reshape(1,3)
V[:,1] =    v2.reshape(1,3)
V[:,2] =    v3.reshape(1,3)

P = P1-P2
t = np.matmul( np.linalg.inv(V), P)

# solve for L1 and L2
L1 = P1 + t[0] * v1
L2 = P2 + t[1] * v2
M = 0.5 * (L1+L2)
REM = .5 * t[2][0]
print("The symbolic intersection is: \n", M,
      "\nwith REM of ", REM)

The symbolic intersection is: 
 [[0. ]
 [0. ]
 [2.5]] 
with REM of  -2.5


## Symbolic Intersection of $n$ Lines in 3D

One utility of computing the intersection of $n$ lines in {term}`3D` is to find the centre of the volume in a reconstructed CT volume.

```{figure} ./../images/002/fig_rotational_xray_reconstruction.png
:label: fig_rotational_xray_reconstruction
:alt: Rotational X-ray Reconstruction.
:align: center
:width: 80%

Rotational X-ray Reconstruction, where center of the imaged volume is the intersection of multiple lines in 3D.
```
First, write the equation for all ines

$$
\begin{align}
L_1 & = & P_1 + t_1 v_1\\
L_2 & = & P_2 + t_2 v_2\\
& \cdots & \\
L_n & = & P_n + t_n v_n\\
\end{align}
$$

The the problem of computing the symbolic intersection can be posed as a least-square optimization with the cost function of:

$$
S = {d_1}^2 + {d_2}^2 + \cdots + {d_n}^2
$$
and compute $M$ where $S$ is the minimum.

```{figure} ./../images/002/fig_n_lines_intersection.png
:label: fig_n_lines_intersection
:alt: Intersection of N lines
:align: center
:width: 80%

Intersection of $n$ lines in 3D where the point $M$ is the symbolic intersection, having the shortest sum of distance from all $n$ lines.
```

Throughout the optimization process, one should always be mindful of deriving and monitoring error metrics including [Root Mean Square](https://en.wikipedia.org/wiki/Root_mean_square) ({term}`RMS`), [average](https://en.wikipedia.org/wiki/Average) ({term}`Avg`), and [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) ({term}`STD`), and use them a means to detect and remove **<wiki:Outlier>**. For example, an <wiki:outlier> can be defined as:

$$
\left| Avg - d_i \right| > (k \cdot STD )
$$

or

$$
\left| RMS - d_i \right| > (k \cdot STD )
$$
(typically $k=2$ or $k=1$). Once outlier is detected, they are moved from the population and the optimization is recomputed, so are the error metrics. This process is repeated until no outlier is left, or the input data is completely removed (a bad situation).

**One easy way** to ***approximate*** the symbolic intersection point $M$ is to compute pairwise intersections for all pairs $(M_{12}, M_{13}, \cdots, M_{1n}, M_{23}, \cdots)$ and approximate $M$ as the average, i.e. {term}`COG`, of these pairwise intersections:

```{figure} ./../images/002/fig_n_lines_intersection2.png
:label: fig_n_lines_intersection2
:alt: Approximation of the intersection of N lines
:align: center
:width: 80%

Approximation of the symbolic intersection of $n$ lines in 3D as the centroid of the pair-wise line intersections.
```

If the input is **decent**, i.e. no <wiki:outliers> and all lines come very close, this simple average is *almost* as good as the proper least square minimum.

In fact, there is indeed no <wiki:outlier>, a closed-form [solutoin](https://en.wikipedia.org/wiki/Line%E2%80%93line_intersection#In_more_than_two_dimensions) exist. Let $P_i$ be the fixed point on $i^{th}$ line and $v_i$ be the unit vector along the $i^{th}$ line, then $M$ can be calculated as:

$$
M = \left( \sum_i I - v_i {v_i}^T \right)^{-1} \left( \sum_i \left(I - v_i {v_i}^T \right) P_i \right)
$$

In [94]:
P1 = np.array([[5],                 # 
              [0],
              [0]])
v1 = np.array([[1],                 # 
              [0],
              [0]])
P2 = np.array([[0],                 # 
              [0],
              [9]])
v2 = np.array([[0],                 # 
              [1],
              [0]])
P3 = np.array([[1],                 # 
              [1],
              [0]])
v3 = np.array([[0],                 # 
              [0],
              [1]])

# initialization
I = np.identity(3)
Sum1 = np.zeros((3,3))
Sum2 = np.zeros((3,1))
# 1st point
Sum1 += I-v1@v1.T
Sum2 += np.matmul(I-(v1@v1.T), P1)

# second point
Sum1 += I-v2@v2.T
Sum2 += np.matmul(I-(v2@v2.T), P2)

# third point
Sum1 += I-v3@v3.T
Sum2 += np.matmul(I-(v3@v3.T), P3)

# solution
M = np.matmul(np.linalg.inv(Sum1), Sum2)
print(M)

[[0.5]
 [0.5]
 [4.5]]


This is a good time to learn about iterative solution vs a closed-form solution.  In mathematics, a closed-form solution is often optimal with regarding to certain error metric, in this case, the Euclidean distance. However, closed-form solution are sensitive to <wiki:outlier>. 

On the other hand, iterative solution (i.e. via optimization) may not reach a solution that is optimal with respect to the given error metric. However, it allows rooms to integrate outlier detection and removal naturally during the iterative process.

## Cartesian Equations of Sphere and Ellipsoid

<wiki:Spheres> and <wiki:ellipsoid> are often used to approximate the size of anatomical structures, such as a tumour, in 3D from medical imaging.

```{figure} ./../images/002/fig_sphere_ellipsoid.png
:label: fig_sphere_ellipsoid
:alt: Sphere and ellipsoid to determine sizing.
:align: center
:width: 80%

Sphere and ellipsoid are used to determine the size of anatomical structures in 3D, image courtesy of Prof. Gabor Fichtinger at Queen's University, Canada.
```

A sphere is represented by its center $C(x_0, y_0, z_0)$ and the radius $R$, with the corresponding equation of:

$$
(x-x_0)^2 + (y-y_0)^2 + (z-z_0)^2 = R^2
$$
which can be used to test if a point $P=(x,y,z)$ is on the surface of the sphere or not.

```{figure} ./../images/002/fig_sphere.png
:label: fig_sphere
:alt: ellipsoid
:align: center
:width: 80%

A sphere is defined by its center $C$ and a radius $R$.
```

An ellipsoidis represented by its center $C(x_0, y_0, z_0)$ and the lengths of principal axes $(a,b,c)$:

```{figure} ./../images/002/fig_ellipsoid.png
:label: fig_ellipsoid
:alt: ellipsoid
:align: center
:width: 80%

An ellipsoid is defined by its center $C$ and the lengths of principal axes.
```
mathematically represented as

$$
\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}+\frac{(z-z_0)^2}{c^2}=1
$$